<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * CharacterToSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterToSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
