<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * CharacterToCyberwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterToCyberwareRepository extends \Doctrine\ORM\EntityRepository
{
}
