<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * CharacterSkillToSpecializationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSkillToSpecializationRepository extends \Doctrine\ORM\EntityRepository
{
}
