<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * ConnectionInDBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionInDBRepository extends \Doctrine\ORM\EntityRepository
{
}
