<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * ConnectionNotInDBRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionNotInDBRepository extends \Doctrine\ORM\EntityRepository
{
}
