<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * CyberwareLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CyberwareLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
