<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * EquipItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipItemRepository extends \Doctrine\ORM\EntityRepository
{
}
