<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * MagicalCapabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicalCapabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
