<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * MagicalTraditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicalTraditionRepository extends \Doctrine\ORM\EntityRepository
{
}
