<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * SpecalizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecalizationRepository extends \Doctrine\ORM\EntityRepository
{
}
