<?php

namespace CharacterDatabaseBundle\Repository;

/**
 * TotemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotemRepository extends \Doctrine\ORM\EntityRepository
{
}
