character_database_homepage:
    path:     /
    defaults: { _controller: CharacterDatabaseBundle:Default:index }

character_list:
    path:     /character
    defaults: { _controller: CharacterDatabaseBundle:Character:index }

character_show:
    path:     /character/{id}
    defaults: { _controller: CharacterDatabaseBundle:Character:show }
    requirements:
        id:  \d+

user_list:
    path:     /user
    defaults: { _controller: CharacterDatabaseBundle:User:index }

user_show:
    path:     /user/{id}
    defaults: { _controller: CharacterDatabaseBundle:User:show }
    requirements:
        id:  \d+

user_logged_in:
    path:     /user/loggedIn
    defaults: { _controller: CharacterDatabaseBundle:User:isLoggedIn }