services:
    character_database.character_service:
        class: CharacterDatabaseBundle\Service\CharacterService\Service
        arguments: ["@logger"]
    character_database.authentication_entry_point:
        class: CharacterDatabaseBundle\Service\Authentication\AuthenticationEntryPoint
        arguments: ["@logger"]


    character_database.cyberwarelevel_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - CharacterDatabaseBundle\Entity\CyberwareLevel

