services:
    character_database.character_service:
        class: CharacterDatabaseBundle\Service\CharacterService\Service
        arguments: ["@logger"]
    character_database.authentication_entry_point:
        class: CharacterDatabaseBundle\Service\Authentication\AuthenticationEntryPoint
        arguments: ["@logger"]
